services:
  lepiaf\SapientBundle\EventSubscriber\SealResponseSubscriber:
    arguments:
      - '@Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory'
      - '@Symfony\Bridge\PsrHttpMessage\Factory\DiactorosFactory'
      - '@ParagonIE\Sapient\Sapient'
      - '@lepiaf\SapientBundle\Service\PublicKeyGetter'
    tags:
      -
        name: kernel.event_subscriber
  lepiaf\SapientBundle\Service\PublicKeyGetter:
      arguments:
        - "%sapient.client_public_keys%"
        - "%sapient.server_public_keys%"
