services:
  lepiaf\SapientBundle\GuzzleHttp\Middleware\SignRequestMiddleware:
    arguments:
      - '@ParagonIE\Sapient\Sapient'
      - '%sapient.sign.private%'
    tags:
      - { name: 'csa_guzzle.middleware', alias: 'sign_request' }
