services:
    lepiaf\SapientBundle\Service\PublicKeyGetter:
        arguments:
          - "%sapient.client_public_keys%"
          - "%sapient.server_public_keys%"
    lepiaf\SapientBundle\GuzzleHttp\Middleware\VerifyResponseMiddleware:
        arguments:
            - '@ParagonIE\Sapient\Sapient'
            - '@lepiaf\SapientBundle\Service\PublicKeyGetter'
            - '@Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory'
        tags:
            - { name: 'csa_guzzle.middleware', alias: 'verify_response', priority: 1 }
