services:
  lepiaf\SapientBundle\GuzzleHttp\Middleware\VerifyResponseMiddleware:
    arguments:
      - '@ParagonIE\Sapient\Sapient'
      - '@lepiaf\SapientBundle\Service\PublicKeyGetter'
    tags:
      - { name: 'csa_guzzle.middleware', alias: 'verify_response', priority: 1 }
